version: '3.8'
services:
  app:
    build: .
    container_name: web-service-authentifaction-app
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network
    command: ["nodemon", "app.js"]

  mongo:
    image: mongo:5
    container_name: web-service-authentifaction-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: